services:
  app:
    container_name: "${image_path}"
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env
    ports:
      - "4000:3000"
    restart: unless-stopped
    networks:
      - nuxt-template-network
    environment:
      - NODE_ENV=$NODE_ENV
      - DATABASE_URL=$DATABASE_URL
      - NUXT_MAIL_USER=$NUXT_MAIL_USER
      - NUXT_MAIL_PASS=$NUXT_MAIL_PASS

volumes:
  nuxt-template-data:

networks:
  nuxt-template-network:
    driver: bridge